src/basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\helpers\Console;
use app\models\Validar;
use app\models\Producto;
use app\models\FrmValidar;
use app\models\Stock;
use app\models\TblUsuario;
use app\models\TblValidar;
use app\models\TblProducto;
use app\models\TblStock;
use app\models\Estado;
use app\models\SeguimientoTramite;
use app\models\NotasExpedientes;
use app\models\NotasExpedientesSearch;
use \app\models\EstudioImpactoAmbiental;


use app\models\Query;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\data\Pagination;



class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionHola($nav="Valor a recibir")
    {
        $variable = 'Valor a mostrar2';
        $mensaje = 'Mensaje...';
        $arreglo = ['Valor0', 'Valor1', 'Valor2', 'Valor3', 'Valor4', 'Valor5'];

        return $this->render('hola', 
            [
            'variable'=>$variable,
            'mostrar'=>$mensaje,
            'arreglo'=>$arreglo,
            'nav'=>$nav
            ]
        );
    }

    public function actionForm($mensaje=null)
    {
        return $this->render('form', ["mensaje"=>$mensaje]);
    }

    public function actionSform()
    {
        $mensaje=null;
         
        if (isset($_REQUEST["nombre"]))
        {
            $mensaje="El nombre es: ".$_REQUEST["nombre"];
        }
        return $this->redirect(['site/form', "mensaje"=>$mensaje]);
    }

    public function actionValidar()
    {
        $model = new Validar;
        
        $mensaje = null;
         
        if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
        {
            //consultas, calculos, etc
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post()))
        {
            if ($model->validate())
            {
                $tbl = new TblValidar;
                $tbl->nombre = $model->nombre;
                $tbl->email = $model->email;
                if ($tbl->insert())
                {
                    $mensaje="Su email fue guardado";
                    $model->nombre=null;
                    $model->email=null;
                }
                else
                {
                    $mensaje="Ha ocurrido un Error al insertar";
                }
                //consultas, calculos, etc
            }
            else
            {
                $model->getErrors();
            }
        }
        return $this->render('validar', ['model'=>$model, 'mensaje'=>$mensaje]);
    }



    public function actionProducto(){
        $model = new Producto();
        $mensaje = null;

        if($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax){
            Yii::$app->request->format = Response :: FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if($model->load(Yii::$app->request->post()))
        {
            if($model->validate()){

                $tbl = new TblProducto;
                $tbl->nombre = $model->nombre;
                $tbl->codigo = $model->codigo;
                $tbl->cantidad = $model->cantidad;
                $tbl->detalle = $model->detalle;

                
                if ($tbl->insert())
                {
                    $mensaje="Su email fue guardado aaaaaaaaaaaaa";
                    $model->nombre=null;
                    $model->detalle=null;
                    $model->codigo=null;
                    $model->cantidad=null;
                }
                else
                {
                    $mensaje="Ha ocurrido un Error al insertar";
                }
                //con


            }else{
                $model->getErros();
            }

        }
        return $this->render('producto', ['model'=>$model, 'mensaje'=>$mensaje]);
    }


    public function actionForm1($mensaje=null){

        return $this->render('form1',["mensaje"=>$mensaje]);


    }

    //aca recivimos el get del formulario
    public function actionSform1(){
        $datotxt=null;

        if (isset(is_REQUEST['campotxt']))
        {
            $datotxt= "el valor enviado el foirm es :". is_REQUEST['campotxt'];

        }

        return $this->redirect(['site/form1', "mensaje"=>$datotxt]);


    }

    public function actionFrmvalidar()
    {
        $model = new FrmValidar();
        $mensaje = null;

        if($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax){
            Yii::$app->request->format = Response :: FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if($model->load(Yii::$app->request->post()))
        {
            if($model->validate()){
                
                $tbl = new TblUsuario;
                $tbl->nombre = $model->nombre;
                $tbl->email = $model->email;
                if ($tbl->insert())
                {
                    $mensaje="Su email fue guardado";
                    $model->nombre=null;
                    $model->email=null;
                }
                else
                {
                    $mensaje="Ha ocurrido un Error al insertar";
                }
                //con


            }else{
                $model->getErros();
            }

        }
        return $this->render('frmvalidar', ['model'=>$model, 'mensaje'=>$mensaje]);
    }
    public function actionStock(){
        $model = new Stock();
        $mensaje = null;

        if($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax){
            Yii::$app->request->format = Response :: FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if($model->load(Yii::$app->request->post()))
        {
            if($model->validate()){

                $tbl = new TblStock;
                $tbl->id_producto = $model->id_producto;
                $tbl->cantidad = $model->cantidad;
                $tbl->fecha = $model->fecha;

                
                if ($tbl->insert())
                {
                    $mensaje="Su email fue guardado ";
                    $model->id_producto=null;
                    $model->fecha=null;
                    $model->cantidad=null;
                }
                else
                {
                    $mensaje="Ha ocurrido un Error al insertar";
                }
            
                
                $mensaje="Su email fue guardado aaaaaaaaaaaaa";
            }else{
                $model->getErros();
            }

        }
        return $this->render('stock', ['model'=>$model, 'mensaje'=>$mensaje]);
    }
    
    public function actionFormview($mensaje=null)
    {
        $model = new Query;

        if ($model->load(Yii::$app->request->get()))
        {
            if ($model->validate())
            {
                $search = Html::encode($model->query);
                $table = TblValidar::find()
                        ->where(['like', 'id', $search])
                        ->orWhere(['like', 'nombre', $search])
                        ->orWhere(['like', 'email', $search]);
            }
            else
            {
                $model->getErrors();
            }
        }
        else
        {
            $table = TblValidar::find();
        }
        $count = clone $table;

src/basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1>Otro valor: <?= Html::encode($this->title) ?></h1>

    <p>
        Valor fijo. This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

src/basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

src/basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

src/basic/views/site/form.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<h1>Form de Prueba</h1>
<h3><?= $mensaje ?></h3>

<h3><?= $_ENV['DB_DATABASE'] ?></h3>

<?= Html::beginForm(
        Url::toRoute("site/sform"), //accion
        "get", //method
        ['class'=>'form-inline'] //options
);
?>

<div class="form-group">
    <?= Html::label("Nombre: ", "nombre") ?>
    <?= Html::textInput("nombre", null, ["class"=>"form-control"]) ?>
</div>

<?= Html::submitInput("Enviar el nombre", ["class"=>"btn btn-primary"]) ?>

<?= Html::endForm() ?>

src/basic/views/site/form1.php
<?php
use yii\helpers\URL;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>


<h1></h1>

<?= Html::beginForm (    
    Url::toRoute('site/sform1'),
    'get',
    ['class'=>'form-inline']
    )

?>
<div class="form-group">
    <?= Html::label("Label del campo","IDcampotxt") ?>
    <?= html::textInput("IDcampotxt", null) ?>

</div>

<?= Html::submitInput("enviar form",["class"=> "btn-primary"]) ?>



<?= Html::endForm()?>

src/basic/views/site/frmvalidar.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<h1>Formulario validar 2</h1>

<h3><?= $mensaje?></h3>

<?php
$form= ActiveForm::begin([
    "method" =>"post",
    "id" => "formulario",
    "enableClientValidation"=>true,
    "enableAjaxValidation"=> false
    ]);
?>

<div class ="form-group">
    <?= $form->field($model,"id")->input("text") ?>
</div>

<div class ="form-group">
    <?= $form->field($model,"nombre")->input("text") ?>
</div>



<div class ="form-group">
<?= $form->field($model,"email")->input("email") ?>
</div>

<?= Html::submitInput("enviar", ["class"=> "btn-primary"]) ?>



<?php
$form->end()
?>

src/basic/views/site/notasexpediente_grilla.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\data\Pagination;
use yii\widgets\LinkPager;

?>

<a href="<?= Url::toRoute("site/notasexpedientes") ?>">Nuevo...</a>

<h3>Lista de la notas y expedientes...</h3>

<h3><?= $mensaje ?></h3>

<?php
    $form = ActiveForm::begin([
        "method"=>"get",
        "action"=> Url::toRoute("site/notasexpediente_grilla"),
        "enableClientValidation"=>true
    ]);
?>

<div class="form-group">
    <?= $form->field($model, "query")->input("search") ?>
</div>

<?= Html::submitInput("Buscar", ["class"=>"btn btn-primary"]) ?>

<?php
    $form->end()
?>



<table class="table table-bordered">
    <tr>
        <th>
            Nro tramite:
        </th>
        <th>
            Estado:
        </th>
        <th>
            Resumen:
        </th>
        <th>
            Acciones
        </th>
    </tr>
    <?php foreach ($data as $row): ?>
    <tr>    
        <td><?= $row->nro_tramite ?></td>
        <td><?= $row->estado ?></td>
        <td><?= $row->resumen ?></td>
        <td><a href="<?= Url::toRoute(["site/delusuario", 'id'=>$row->id]) ?>">Eliminar</a>
            <a href="<?= Url::toRoute(["site/actualizarnotas_expediente", 'id'=>$row->id]) ?>">Editar</a>
        </td>
    </tr>
    <?php endforeach ?>

</table>
<?= LinkPager::widget([
        "pagination"=>$pages
    ])
?>

src/basic/views/site/notasexpedientes.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Estado;
use app\models\Destinatario;

/* @var $this yii\web\View */
/* @var $model app\models\NotasExpedientes */
/* @var $form ActiveForm 
<?= $form->field($model, 'id')->input("text")  ?>
*/
?>

<h3><?= $mensaje?></h3>

<div class="NotasExpedientes">

    <?php $form = ActiveForm::begin(); ?>
        
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'nro_tramite')->input("text")  ?>
                <?= $form->field($model, 'tramite_original')->input("text")  ?>
                <?= $form->field($model, 'estado')->dropDownList(
                    ArrayHelper::map(Estado::find()->all(),'id','descripcion' ), 
                                    ['prompt' => 'Seleccione Uno']
                );  ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'nro_expte_nota')->input("text")  ?>
                <?= $form->field($model, 'fec_expt')->input("date")  ?>
                <?= $form->field($model, 'fec_llegada_viedma')->input("date")  ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'caratula_expte_nuevo')->input("text")  ?>
                <?= $form->field($model, 'fec_ingreso')->input("date")  ?>
                <?= $form->field($model, 'fojas')->input("text")  ?>
            </div>
        </div>
    </div>
        <?= $form->field($model, 'resumen')->input("text")  ?>
        <?= $form->field($model, 'remitente')->input("text")  ?>
        <?= $form->field($model, 'observaciones')->input("text")  ?>
        <div class="form-group">
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
            <?= Html::submitButton('Imprimir Pase ', ['name' => 'print_pase', 'value' => 'print_pase','class' => 'btn btn-primary']) ?>
            <?= Html::submitButton('Imprimir Encabezado',[ 'name'=>'print_encabezado', 'value' => 'print_encabezado','class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

    </div><!-- NotasExpedientes -->


    <div class="SeguimientoTramiteForm">
        <div class="container-fluid">
                        <?php $formFour = ActiveForm::begin([
        'method' => 'post',
        'action' => yii\helpers\Url::to(['site/seguimientotramite']),
])           ?>

            <div class="row">
                <div class="col-md-4">
                 
                    <!--  $formFour->field($model2, 'id_nota_expet',)->textInput()->hint('Please enter your name')->input('text') 
    -->
                    <?= $formFour->field($model2, 'id_nota_expet')->input('text') ?>
                  
                    <?= $formFour->field($model2, 'id_destinatario')->dropDownList(
                    ArrayHelper::map(Destinatario::find()->all(),'id','descripcion' ), 
                                    ['prompt' => 'Seleccione Uno']
                    );  ?>
                </div>
                <div class="col-md-4">
                    <?= $form->field($model2, 'estado_tramite')->dropDownList(
                            ArrayHelper::map(Estado::find()->all(),'id','descripcion' ), 
                                    ['prompt' => 'Seleccione Uno']
                    );  ?>
 
                </div>
                <div class="col-md-4">
                    <?= $formFour->field($model2, 'fecha_pase')->input("date") ?>
                    <div class="form-group">
                        <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
                    </div>
                </div>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div><!-- SeguimientoTramiteForm -->

src/basic/views/site/pasesexpedientes.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
                        use app\models\Estado;
use app\models\Destinatario;

/* @var $this yii\web\View */
/* @var $model app\models\EstudioImpactoAmbiental */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Estudio Impacto Ambientals', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="estudio-impacto-ambiental-view">

    <h1>Pases de expedientes Renglon : <?= Html::encode($model->reglon) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'reglon',
            'empresa',
            'referencia',
            'consultor',
            'localidad',
            'nro_expte_mineria',
            'fec_recepcion',
            'fec_nota',
            'numero_Nota',
            'fojas_recepcion',
            'observaciones:ntext',
            'revision',
            'secto_Revision',
            'fec_ultimo_pase',
            'ultimo_tramite',
            'ult_usu',
        ],
    ]) ?>

</div>


    <div class="SeguimientoTramiteForm">
        <div class="container-fluid">
            <?php $formFour = ActiveForm::begin();
            $formFour->action= yii\helpers\Url::to('site\SeguimientoTramite');
            ?>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">        
                        <?= $formFour->field($model2, 'id_nota_expet')->input("text") ?>
                   </div> 
                </div> 
                <div class="col-md-3"> 
                    <div class="form-group">        
                    <?= $formFour->field($model2, 'id_destinatario')->dropDownList(
                        ArrayHelper::map(Destinatario::find()->all(),'id','descripcion' ), 
                                        ['prompt' => 'Seleccione Uno']
                        );  ?>
                    </div>
                </div>
                 <div class="col-md-3">
                    <div class="form-group">
                       <?= $formFour->field($model2, 'estado_tramite')->dropDownList(
                            ArrayHelper::map(Estado::find()->all(),'id','descripcion' ), 
                                    ['prompt' => 'Seleccione Uno']
                        );  ?>
                     </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <?= $formFour->field($model2, 'fecha_pase')->input("date") ?>
                    </div>
                </div>
                 <div class="form-group">
                        <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
                 </div>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div><!-- SeguimientoTramiteForm -->

src/basic/views/site/producto.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<h1>Formulario producto</h1>

<h3><?= $mensaje?></h3>

<?php
$form= ActiveForm::begin([
    "method" =>"post",
    "id" => "formulario",
    "enableClientValidation"=>true,
    "enableAjaxValidation"=> false
    ]);
?>

<div class ="form-group">
    <?= $form->field($model,"id")->input("text") ?>
</div>

<div class="form-group">
    <?= $form ->field($model,"nombre")->input("text")?>
</div>
<div class= "form-group">
<?= $form ->field($model,"detalle")->input("text")?>
</div>
<div class= "form-group">
    <?= $form ->field($model,"codigo")->input("text") ?>
</div>
<div class= "form-group">
    <?= $form->field($model,"cantidad")->input("text") ?>
</div>

<?= Html::submitInput("enviar", ["class"=> "btn-primary"]) ?>



<?php
$form->end()
?>

src/basic/views/site/stock.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

?>

<h1>Formulario stock</h1>

<h3><?= $mensaje?></h3>

<?php
$form= ActiveForm::begin([
    "method" =>"post",
    "id" => "formulario",
    "enableClientValidation"=>true,
    "enableAjaxValidation"=> false
    ]);
?>

<div class ="form-group">
    <?= $form->field($model,"id")->input("text") ?>
</div>
<div class ="form-group">
    <?= $form->field($model,"id_producto")->input("text") ?>
</div>


<div class= "form-group">
    <?= $form ->field($model,"cantidad")->input("text") ?>
</div>
<div class= "form-group">
<?= $form->field($model,'fecha')->input("date") ?>
</div>

<?= Html::submitInput("enviar", ["class"=> "btn-primary"]) ?>



<?php
$form->end()
?>

src/basic/views/site/test.php
<?php 
    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
    use yii\helpers\Url;
?>


<h1><?= Html::encode($variable) ?></h1>



<?php $form = ActiveForm::begin([   'id' => 'order-search-form',
    'method' => 'get']); ?>

    <div>
    <?= $form->field('test')->textInput() ?>
    </div>


    <div class="form-group">
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>



<?php ActiveForm::end(); ?>

src/basic/views/site/validar.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
?>

<h1> Formulario Validado </h1>
<h3><?= $mensaje ?></h3>

<a href="<?= Url::toRoute("site/formview") ?>">Lista</a>

<?php
    $form = ActiveForm::begin([
        "method"=>"post",
        "id" => "formulario",
        "enableClientValidation"=>false,
        "enableAjaxValidation"=>true
    ]);
?>

<div class="form-group">
    <?= $form->field($model, "id")->input("text") ?>
</div>

<div class="form-group">
    <?= $form->field($model, "nombre")->input("text") ?>
</div>

<div class="form-group">
    <?= $form->field($model, "email")->input("email") ?>
</div>

<?= Html::submitInput("Enviar", ["class"=>"btn btn-primary"]) ?>

<?php
    $form->end()
?>

src/basic/views/site/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
                        use app\models\Estado;
use app\models\Destinatario;

/* @var $this yii\web\View */
/* @var $model app\models\EstudioImpactoAmbiental */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Estudio Impacto Ambientals', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="estudio-impacto-ambiental-view">

    <h1>Pases de expedientes Renglon : <?= Html::encode($model->reglon) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'reglon',
            'empresa',
            'referencia',
            'consultor',
            'localidad',
            'nro_expte_mineria',
            'fec_recepcion',
            'fec_nota',
            'numero_Nota',
            'fojas_recepcion',
            'observaciones:ntext',
            'revision',
            'secto_Revision',
            'fec_ultimo_pase',
            'ultimo_tramite',
            'ult_usu',
        ],
    ]) ?>

</div>


    <div class="SeguimientoTramiteForm">
        <div class="container-fluid">
            <?php $formFour = ActiveForm::begin();
            $formFour->action= yii\helpers\Url::to('site\SeguimientoTramite');
            ?>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">        
                        <?= $formFour->field($model2, 'id_nota_expet')->input("text") ?>
                   </div> 
                </div> 
                <div class="col-md-3"> 
                    <div class="form-group">        
                    <?= $formFour->field($model2, 'id_destinatario')->dropDownList(
                        ArrayHelper::map(Destinatario::find()->all(),'id','descripcion' ), 
                                        ['prompt' => 'Seleccione Uno']
                        );  ?>
                    </div>
                </div>
                 <div class="col-md-3">
                    <div class="form-group">
                       <?= $formFour->field($model2, 'estado_tramite')->dropDownList(
                            ArrayHelper::map(Estado::find()->all(),'id','descripcion' ), 
                                    ['prompt' => 'Seleccione Uno']
                        );  ?>
                     </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <?= $formFour->field($model2, 'fecha_pase')->input("date") ?>
                    </div>
                </div>
                 <div class="form-group">
                        <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
                 </div>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div><!-- SeguimientoTramiteForm -->